// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHUk27n00aOkBwB92rPUE6NjrgFx1XLSM',
    appId: '1:923423066678:web:2c469b560b905ff728e697',
    messagingSenderId: '923423066678',
    projectId: 'qrlabel-3f95c',
    authDomain: 'qrlabel-3f95c.firebaseapp.com',
    storageBucket: 'qrlabel-3f95c.appspot.com',
    measurementId: 'G-G8CKWXFK91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdy_dPIa_LV6LlcYY8sU01jd4EIsMbCMw',
    appId: '1:923423066678:android:a55245d449c3567b28e697',
    messagingSenderId: '923423066678',
    projectId: 'qrlabel-3f95c',
    storageBucket: 'qrlabel-3f95c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIVOZeu05zinqUPEhuErDWY-r2g7BxZC8',
    appId: '1:923423066678:ios:28afc3339b53c52e28e697',
    messagingSenderId: '923423066678',
    projectId: 'qrlabel-3f95c',
    storageBucket: 'qrlabel-3f95c.appspot.com',
    iosBundleId: 'com.example.qrLabel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIVOZeu05zinqUPEhuErDWY-r2g7BxZC8',
    appId: '1:923423066678:ios:f45a400ccd2d8ca428e697',
    messagingSenderId: '923423066678',
    projectId: 'qrlabel-3f95c',
    storageBucket: 'qrlabel-3f95c.appspot.com',
    iosBundleId: 'com.example.qrLabel.RunnerTests',
  );
}
